---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! "$(docker stats --no-stream)" ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t redis:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - tag
    - push

- name: scan-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  environment:
    IMAGE_NAME: redis:${DRONE_COMMIT_SHA}
    FAIL_ON_DETECTION: false
  when:
    event:
      exclude:
        - tag
        - pull_request

- name: deploy_image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - if [[ "$${DRONE_BRANCH}" == "master" ]] || [[ -n "$${DRONE_TAG}" ]]; then
    docker login -u="$${REGISTRY_USER}" -p="$${DOCKER_PASSWORD}" $${REPO};
    docker tag redis:$${DRONE_COMMIT_SHA} $${REPO}/$${AUTHOR}/$${NAME}:$${DRONE_TAG:-latest};
    docker push $${REPO}/$${AUTHOR}/$${NAME}:$${DRONE_TAG:-latest};
    fi
  environment:
    AUTHOR: ukhomeofficedigital
    DOCKER_PASSWORD:
      from_secret: docker_password
    NAME: docker-redis
    REGISTRY_USER: ukhomeofficedigital+drone_docker_redis
    REPO: quay.io
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  when:
    event:
      exclude:
        - pull_request

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  commands:
    - /run.sh server
  when:
    event:
      exclude:
        - tag
        - pull_request
