pipeline:

  build_docker_image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t redis:$${DRONE_COMMIT_SHA} . --no-cache

  latest_image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_docker_redis" -p="$${DOCKER_PASSWORD}" quay.io
      - docker tag redis:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/redis:latest
      - docker tag redis:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/redis:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/redis:latest
      - docker push quay.io/ukhomeofficedigital/redis:$${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master

  tag_image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_docker_redis" -p="$${DOCKER_PASSWORD}" quay.io
      - docker tag redis:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/redis:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/redis:$${DRONE_TAG}
    when:
      event: tag
