apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    name: redis
